@startuml addTeam

actor User as U
participant Application as A

activate U
activate A

U->A: Add team information
A-->U: Displays team information
U->A: Clicks "Add Player"/"Add Team"
A-->U: Displays the team
A-->U: Clears the input fields


@enduml