@startuml SequenceOpen 

actor User as U
participant Application as A
database Database as D

activate U
activate A

U->A: Opens application
A-->U:Displays overview page
activate D
A->D: Sends query to the "Tournament" table
D-->A: Receives data from database
deactivate D
A-->U: Displays the previous tournaments






@endumel