@startuml createTournament

actor User as U
participant Application as A
Database Database as D

activate U
activate A

U->A: Clicks on the x next to a tournament name
A-->U: Opens the confirmation box
alt confirms
    U->A: Clicks the "Yes" button
    A-->U: Closes the confirmation box
    activate D
    A->D: Deletes tournament from database
    D-->A: Confirms deletion
    deactivate D
    A-->U: Deletes tournament from overview page
else Denies
    U->A: Clicks the "No" button
    A-->U: Closes the confirmation box

end



@enduml