@startuml SequenceOpen 

actor User as U
participant Application as A
database Database as D

activate U
activate A

U->A: Presses the "overview" button
A-->U:Display overview page
activate D
A->D: Sends querry to Tournament database table
D-->A: Sends data to application
deactivate D
A-->U: Displays the previous tournaments






@endumel