@startuml SequenceOpen 

actor User as U
participant Application as A
database Database as D

activate U
activate A

U->A: Clicks the "Overview" button
A-->U: Display the overview page
activate D
A->D: Sends query to the "Tournament" database table
D-->A: Sends data to the application
deactivate D
A-->U: Displays the previous tournaments






@endumel