@startuml ConfigureSettings

actor User as U
participant Application as A
participant Database as D

activate U
activate A

U->A: Clicks "Setup Tournament"
A-->U: Opens and displays the page
U->A: Presses the New Tournament button
A-->U: Opens the settings page
U->A: Enter the settings
A-->U: Uppdates the GUI to match the changes
U->A: Clicks "Setup Tournament"
activate D
A->D: Request next tournamentID and next team ID
D-->A:Retrives requested data
deactivate D
A-->U: Opens and displays the page to add teams



@enduml