@startuml SequenceOpen 

actor User as U
participant Application as A
database Database as D

activate U
activate A

U->A: Open application
A-->U:Display overview page
activate D
A->D: Sends query to Tournament table
D-->A: Receives data from database
deactivate D
A-->U: Displays the previous tournaments






@endumel