@startuml createTournament

actor User as U
participant Application as A

activate U
activate A

U->A: Clicks on the "x" next to a team/player
A-->U: Opens the confirmation box
alt Confirms
    U->A: Presses "yes"
    A-->U: Closes confirmation box
    A-->U: Delete team/player from page
else Denies
    U->A: Presses "no"
    A-->U: Closes confirmation box

end



@enduml