@startuml editMatch

actor User as U
participant Application as A

activate U
activate A


U->A: Clicks on a match number
A-->U: Opens the edit match page
U->A: Enters the score
A-->U: Uppdates the GUI to match the changes
U->A: Clicks the "Update score" button 
A-->U: Sends back to the tournament page 

@enduml