@startuml createTournament

actor User as U
participant Application as A
Database Database as D

activate U
activate A

U->A: Clicks on a tournament name
A-->U: Takes you to the loading page
activate D
A->D: Requests all information about the tournament
D-->A: Sends requested data to the application
deactivate D
A-->U: Takes you to the page for the tournament



@enduml