@startuml createTournament

actor User as U
participant Application as A
Database Database as D

activate U
activate A

U->A: Clicks on the x next to a tournament name
A-->U: opens the confirmation box
alt confirms
    U->A: Presses "yes"
    A-->U: Closes confirmation box
    activate D
    A->D: Deletes tournament from database
    D-->A: Confirms deletion
    deactivate D
    A-->U: Deletes tournament from overview page
else Denies
    U->A: Presses "no"
    A-->U: Closes confirmation box

end



@enduml