@startuml editMatch

actor User as U
participant Application as A

activate U
activate A


U->A: Clicks on a match number
A-->U: Opens the edit match page
U->A: Enter the score
A-->U: Uppdates the GUI to match the changes
U->A: Presses the update score button 
A-->U: Sends back to tournament page 

@enduml