@startuml MachineBorderThicknes


Entity user{
    ⠀ID
    ⠀Password
}


Class team{
    members
    teamName
    AvrageTrophies
}

class teamMember{
    name
    trophies
    clanname
}

Class tournament{
    user
    team
    rounds
    type
}

Class matches{
    result
    team
    victory
}






user "1..1" -- "0..*" tournament : Goes to
teamMember "1,2" -- "1..1" team : Member of 
tournament "1..1" -- "2..*"team : Playing in
tournament "1..1" -- "1..* "matches : Playing in
team"2..2"-- "1..1" matches : Plays in
@enduml