@startuml MachineBorderThicknes


Entity user{

}


Class team{
   
}

class teamMember{
   
}

Class tournament{
   }

Class matches{
    
}






user  --  tournament : Goes to
teamMember  --  team : Member of 
tournament  -- team : Playing in
tournament  --  matches : Playing in
team --  matches : Plays in
@enduml