@startuml MachineBorderThicknes





Class team{
   
}

class teamMember{
   
}

Class tournament{
   }

Class matches{
    
}






teamMember  --  team : Member of 
tournament  -- team : Playing in
tournament  --  matches : Playing in
team --  matches : Plays in
@enduml