@startuml sequence 


actor User as U
participant Aplication as A
participant Database as D

activate U
activate A
activate D



alt Choose already created
    U->A: Select already created tournament
    A->D: Sends request for information
    D-->A: Tournament loads
    A-->U: Selected
else Create new
    U->A: Create new tournament
 
    U->A: Choose tournament type
    A-->U: Tournament type chosen
    
    U->A: Choose match type
    A-->U: Match type chose
    
    U->A: Choose amount of rounds
    A-->U: Aamount of rounds chose
    
    A-->U: Created
    
    loop Loops every time a player is added or deleted
    
        U->A: Add person or team
        A-->U: Added

        U->A: Remove person or team
        A-->U: Removed
    
        U->A: Type in name, clan name and trophies
        A-->U: Typed
        
    
        
    end
    U->A: Create setup and send to tournament page
    A-->U: Tournament ready
end


U->A: Type in scores 
A-->U: Scores updated

U->A: Save tournament
A->D: Saves tournament
D-->A: Tournament saved
A-->U: Tournament saved
